# Header
menu:
  All: /
  Azure: /categories/azure
  # 后端: /categories/back-end
  # 标签: /tags
  # 归档: /archives
  # 订阅: /atom.xml
  # 关于: /about

# Content
# excerpt_link: 阅读更多
content_max_width: 800px

# Sidebar
author:
  name: Joona Luoma
  work: Developer
  location: Tampere, Finland
  avatar_url: /images/space.PNG

# Miscellaneous
rss: /atom.xml
favicon: /images/favicon.ico

# github comment
git_commit:
  enable: false
